"""3 Migration

Revision ID: e2706ce5d035
Revises: 2584e162b8c5
Create Date: 2018-09-11 18:19:30.176039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2706ce5d035'
down_revision = '2584e162b8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('pitch_content', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_reviews_pitch_content'), 'reviews', ['pitch_content'], unique=False)
    op.drop_column('reviews', 'pitch_id')
    op.drop_column('reviews', 'pitch_review')
    op.drop_column('reviews', 'pitch_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('pitch_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('pitch_review', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_reviews_pitch_content'), table_name='reviews')
    op.drop_column('reviews', 'pitch_content')
    # ### end Alembic commands ###
